# Generated by Django 6.0.4 on 2026-04-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('data_quality', models.FloatField(blank=True, null=True)),
                ('meal_inexpensive_restaurant', models.FloatField(blank=True, null=True)),
                ('meal_for_two_mid_range', models.FloatField(blank=True, null=True)),
                ('mcmeal_at_mcdonalds', models.FloatField(blank=True, null=True)),
                ('domestic_beer_restaurant', models.FloatField(blank=True, null=True)),
                ('imported_beer_restaurant', models.FloatField(blank=True, null=True)),
                ('cappuccino', models.FloatField(blank=True, null=True)),
                ('coke_pepsi', models.FloatField(blank=True, null=True)),
                ('water_restaurant', models.FloatField(blank=True, null=True)),
                ('milk_1l', models.FloatField(blank=True, null=True)),
                ('bread_500g', models.FloatField(blank=True, null=True)),
                ('rice_1kg', models.FloatField(blank=True, null=True)),
                ('eggs_12', models.FloatField(blank=True, null=True)),
                ('local_cheese_1kg', models.FloatField(blank=True, null=True)),
                ('chicken_1kg', models.FloatField(blank=True, null=True)),
                ('beef_1kg', models.FloatField(blank=True, null=True)),
                ('apples_1kg', models.FloatField(blank=True, null=True)),
                ('banana_1kg', models.FloatField(blank=True, null=True)),
                ('oranges_1kg', models.FloatField(blank=True, null=True)),
                ('tomato_1kg', models.FloatField(blank=True, null=True)),
                ('potato_1kg', models.FloatField(blank=True, null=True)),
                ('onion_1kg', models.FloatField(blank=True, null=True)),
                ('lettuce', models.FloatField(blank=True, null=True)),
                ('water_1_5l_market', models.FloatField(blank=True, null=True)),
                ('wine_mid_range', models.FloatField(blank=True, null=True)),
                ('domestic_beer_market', models.FloatField(blank=True, null=True)),
                ('imported_beer_market', models.FloatField(blank=True, null=True)),
                ('cigarettes_20pack', models.FloatField(blank=True, null=True)),
                ('one_way_ticket', models.FloatField(blank=True, null=True)),
                ('monthly_pass', models.FloatField(blank=True, null=True)),
                ('taxi_start', models.FloatField(blank=True, null=True)),
                ('taxi_1km', models.FloatField(blank=True, null=True)),
                ('taxi_1hr_wait', models.FloatField(blank=True, null=True)),
                ('gasoline_1l', models.FloatField(blank=True, null=True)),
                ('volkswagen_golf', models.FloatField(blank=True, null=True)),
                ('toyota_corolla', models.FloatField(blank=True, null=True)),
                ('basic_utilities_85m2', models.FloatField(blank=True, null=True)),
                ('mobile_monthly', models.FloatField(blank=True, null=True)),
                ('internet_60mbps', models.FloatField(blank=True, null=True)),
                ('fitness_club_monthly', models.FloatField(blank=True, null=True)),
                ('tennis_court_1hr', models.FloatField(blank=True, null=True)),
                ('cinema_ticket', models.FloatField(blank=True, null=True)),
                ('preschool_monthly', models.FloatField(blank=True, null=True)),
                ('intl_primary_school_annual', models.FloatField(blank=True, null=True)),
                ('jeans_levis', models.FloatField(blank=True, null=True)),
                ('summer_dress', models.FloatField(blank=True, null=True)),
                ('nike_running_shoes', models.FloatField(blank=True, null=True)),
                ('mens_leather_shoes', models.FloatField(blank=True, null=True)),
                ('apt_1br_city_center', models.FloatField(blank=True, null=True)),
                ('apt_1br_outside_center', models.FloatField(blank=True, null=True)),
                ('apt_3br_city_center', models.FloatField(blank=True, null=True)),
                ('apt_3br_outside_center', models.FloatField(blank=True, null=True)),
                ('avg_net_salary', models.FloatField(blank=True, null=True)),
                ('mortgage_rate', models.FloatField(blank=True, null=True)),
                ('price_per_sqm_city_center', models.FloatField(blank=True, null=True)),
                ('price_per_sqm_outside_center', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'city'],
            },
        ),
    ]
